[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
php = "8.4"
node = "22"

[build.nixpacksConfig.variables]
APP_ENV = "production"
NODE_ENV = "production"
COMPOSER_ALLOW_SUPERUSER = "1"
PHP_VERSION = "8.4"
NODE_VERSION = "22"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
path = "/"
interval = "30s"
timeout = "10s"
retries = 3